In [1]:
import numpy as np

In [7]:
A = np.array([[56.0,0.0,4.0,2.3],
              [24.23,54.26,24.85,1.56],
              [2,4,5,6]])
A

array([[56.  ,  0.  ,  4.  ,  2.3 ],
       [24.23, 54.26, 24.85,  1.56],
       [ 2.  ,  4.  ,  5.  ,  6.  ]])

In [6]:
sum_val = A.sum(axis=0)
sum_val

array([82.23, 58.26, 33.85,  9.86])

In [12]:
percentage = 100*A/sum_val

In [13]:
percentage

array([[68.10166606,  0.        , 11.816839  , 23.32657201],
       [29.46613158, 93.13422588, 73.41211226, 15.82150101],
       [ 2.43220236,  6.86577412, 14.77104874, 60.85192698]])