# Python - Numpy Vectors

In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)
a

array([-0.90889104,  0.78343304,  0.56901274,  0.77113313, -1.12435575])

In [6]:
a.T
# the above cell and it is showing same output as this are called rank 1 vector and
# it should not be used as the shape are different from normal m x n
a.shape

(5,)

In [7]:
# we should use when declaring itself
a = np.random.randn(5, 1) # (5,1) ✅ and not ❌ (5)
a

array([[-1.97694207],
       [ 0.98279909],
       [-0.7027627 ],
       [-0.119009  ],
       [ 0.67849154]])

In [8]:
a.T

array([[-1.97694207,  0.98279909, -0.7027627 , -0.119009  ,  0.67849154]])

In [9]:
a.shape

(5, 1)